DROP TABLE IF EXISTS Numbers
GO

CREATE TABLE Numbers (
	Number INT NOT NULL
);

CREATE UNIQUE CLUSTERED INDEX idx_Calendar_Number ON dbo.Numbers (Number);
GO


WITH 
	L0   AS(SELECT 1 AS C UNION ALL SELECT 1 AS O), 
	L1   AS(SELECT 1 AS C FROM L0 AS A CROSS JOIN L0 AS B), 
	L2   AS(SELECT 1 AS C FROM L1 AS A CROSS JOIN L1 AS B), 
	L3   AS(SELECT 1 AS C FROM L2 AS A CROSS JOIN L2 AS B), 
	L4   AS(SELECT 1 AS C FROM L3 AS A CROSS JOIN L3 AS B),
	L5   AS(SELECT 1 AS C FROM L4 AS A CROSS JOIN L4 AS B),
	Ordered AS (SELECT ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS Number FROM L5)
INSERT INTO dbo.Numbers (Number)
SELECT Number
FROM Ordered
WHERE Number <= 2000000
GO
